 

--------------------------------------------------------------DATA ANALYSIS----------------------------------------------------------------------

--Q1: ----------------------------------------------------DATA PREPARATION AND UNDERSTANDING------------------------------------------------------

-- Q1:What is the total number of rows in each of the 3 tables in the database ? 

SELECT COUNT (customer_Id) AS TOTAL_ROWS FROM CUSTOMER

SELECT COUNT(prod_cat) AS TOTAL_ROWS FROM prod_cat_info

SELECT COUNT (transaction_id) AS TOTAL_ROWS FROM Transactions

--1. End

-- Q2: What is the total number of transactions that have a return?

SELECT COUNT(transaction_id) AS Transaction_No
FROM Transactions
WHERE QTY < 0 

--2. End

-- Q3: As you would have noticed, the dates provided across the datasets are not in a correct format. 
--As first steps, pls convert the date variables into valid the date formats before proceeding ahead.

SELECT customer_Id,FORMAT(DOB, 'dd/MM/yyyy') AS Date_Birth,Gender,city_code
FROM Customer

SELECT transaction_id , cust_id,FORMAT (tran_date,'dd/MM/yyyy') AS TransDate ,prod_subcat_code,prod_cat_code,
Qty,Rate,Tax,total_amt, Store_type FROM Transactions

--3. End

-- Q4: What is the time range of the transaction data available for analysis? 
-- Show the output in  number of days, months and years simultaneously in different
-- coulmns.

SELECT DATEDIFF(DAY,MIN(tran_date),MAX(tran_date)) AS [Days], 
DATEDIFF(MONTH,MIN(tran_date),MAX(tran_date)) AS [Months],
DATEDIFF (YEAR, MIN(tran_date), MAX(tran_date)) AS [Years]
FROM Transactions
 
--4. End

--Q5: Which product category does the sub-category "DIY" belong to?

select prod_cat,prod_subcat from prod_cat_info
where prod_subcat = 'DIY'

--5. End

--------------------------------------------------------------DATA ANALYSIS----------------------------------------------------------------------

--Q1: Which channel is most frequently used for transactions?

SELECT TOP 1 Store_type,COUNT(Store_type)  AS Trans_Count FROM Transactions
Group by Store_type
ORDER BY Trans_Count DESC

--1. End

--Q2: What is the count of male and female customers?

SELECT  Gender, COUNT(Gender) AS Gender_Count  
FROM Customer
WHERE Gender IS NOT NULL
GROUP BY Gender

--2. End
 
--Q3: Which city has maximum number of customers and how many?

SELECT TOP 1 city_code, COUNT(customer_Id) AS Cust_Count FROM Customer
GROUP BY city_code  
ORDER BY Cust_Count DESC

--3. End

--Q4: How many sub-categories are there under Books category?

SELECT prod_cat, COUNT(prod_subcat) AS Prod_Subcat
FROM prod_cat_info
GROUP BY prod_cat
HAVING prod_cat = 'Books'

--4. End

--Q5: What is the max quantity of products ever ordered?

SELECT TOP 1 transaction_id,cust_id,MAX(Qty) AS Max_Qty FROM Transactions 
GROUP BY transaction_id,cust_id
ORDER BY Max_Qty DESC

--5. End

--Q6: What is the net total revenue generated in categories Electronics and Books?

SELECT  prod_cat, SUM(total_amt) AS Tot_Revenue FROM prod_cat_info AS P
INNER JOIN Transactions AS T
ON P.prod_cat_code = T.prod_cat_code
			AND
   P.prod_sub_cat_code = T.prod_subcat_code
GROUP BY   prod_cat
HAVING P.prod_cat = 'ELECTRONICS' 
			OR
	P.prod_cat = 'BOOKS'

--6. End

--Q7: How many customers have >10 transactions, excluding returns?

SELECT COUNT(cust_id) AS Cust_Count 
FROM (
		SELECT cust_id,COUNT (transaction_id) AS Trans_Count
		FROM Transactions
		WHERE Qty > 0 
		GROUP BY cust_id
		HAVING COUNT ( transaction_id) > 10 
) AS X

--7. End

--Q8: What is the combined revenue earned from Electronics and Clothing, from Flagship store? 

SELECT SUM(Comb_Revenue) AS COMBINE_REVENUE
FROM (
	SELECT  T.prod_cat_code, SUM (total_amt) AS Comb_Revenue
	FROM prod_cat_info AS P
	INNER JOIN Transactions AS T
	ON P.prod_cat_code = T.prod_cat_code
				AND
		P.prod_sub_cat_code = T.prod_subcat_code
	WHERE Store_type = 'FLAGSHIP STORE'
			AND
		 prod_cat IN ('ELECTRONICS','CLOTHING')
	GROUP BY T.prod_cat_code
) AS X 

--8. End

--Q9: What is the total revenue generated by Male customers in Electronics category?

SELECT prod_subcat ,SUM(Tot_Revenue) AS Total_Revenue
FROM ( 
	SELECT cust_id,Gender,prod_cat, prod_subcat,SUM(total_amt) AS Tot_Revenue FROM Customer AS C 
	INNER JOIN Transactions AS T
	ON C.customer_Id = T.cust_id
	INNER JOIN prod_cat_info AS P
	ON T.prod_cat_code = P.prod_cat_code 
			AND
	   T.prod_subcat_code = P.prod_sub_cat_code
	WHERE prod_cat = 'ELECTRONICS' AND  Gender = 'M'
	GROUP BY cust_id, Gender, prod_cat,prod_subcat
) AS X
GROUP BY prod_subcat

--9. End

--Q10: What is the % of sales and returns by product sub category; display only top 5 sub categories based on sales.

SELECT prod_subcat ,( TOTAL_SALES) / (SELECT SUM(TOTAL_AMT) FROM Transactions WHERE TOTAL_AMT> 0 )* 100 SALES_PERCENT,
RETURN_SALES / (SELECT SUM(TOTAL_AMT) FROM Transactions WHERE TOTAL_AMT < 0 )* 100 AS RETURN_PERCENT
FROM ( 
	SELECT TOP 5 prod_subcat, 
	CAST(SUM(CASE WHEN total_amt >= 0 THEN total_amt ELSE 0 END)  AS FLOAT) AS TOTAL_SALES,
	CAST(SUM(CASE WHEN total_amt < 0 THEN total_amt ELSE 0 END) AS FLOAT ) AS RETURN_SALES
	FROM prod_cat_info AS P
	INNER JOIN Transactions AS T 
	ON P.prod_cat_code = T.prod_cat_code
				AND
		P.prod_sub_cat_code = T.prod_subcat_code
	GROUP BY prod_subcat 
	ORDER BY TOTAL_SALES DESC , RETURN_SALES DESC
) AS X 
GROUP BY PROD_SUBCAT , TOTAL_SALES, RETURN_SALES

--10. End

--Q11: For all customers aged between 25 to 35 years find what is the net total revenue generated by them in last 30 days of transactions?

SELECT SUM(total_amt) AS NET_REVENUE
FROM(
	SELECT   cust_id, tran_date , total_amt  FROM Transactions AS T
	INNER JOIN Customer AS C
	ON T.cust_id = C.customer_Id
	WHERE (YEAR (GETDATE())- YEAR (DOB)) BETWEEN 25 AND 35
			AND
	  DATEDIFF(DAY, tran_date,(SELECT MAX(tran_date) FROM Transactions)) <= 30
)  AS X

--11. End

--Q12: Which product category has seen max value of returns in last 3 months of transactions?

SELECT TOP 1 P.prod_cat, SUM(total_amt) AS TOT_AMT, tran_date 
FROM prod_cat_info AS P 
INNER JOIN Transactions AS T 
ON P.prod_cat_code = T.prod_cat_code
			AND
	P.prod_sub_cat_code = T.prod_subcat_code
WHERE total_amt < 0 
		AND
	 tran_date >= DATEADD (MONTH, -3 , (SELECT MAX(tran_date) FROM Transactions))
GROUP BY  tran_date ,prod_cat  
ORDER BY TOT_AMT DESC

--12. End

--Q13: Which store type sells the max products;by value of sales amount and quantity sold?

SELECT TOP 1 SUM(Qty) AS QTY,SUM(total_amt)AS TOTAL_AMOUNT,Store_type FROM Transactions
WHERE Qty > 0 
GROUP BY  Store_type 
ORDER BY QTY DESC 

--13. End

--Q14: What are the categories for which average revenue is above overall average?

SELECT prod_cat, AVG(total_amt) AS AVERAGE_AMT FROM Transactions AS T
INNER JOIN prod_cat_info AS P 
ON T.prod_cat_code = P.prod_cat_code
			AND
	T.prod_subcat_code = P.prod_sub_cat_code
GROUP BY prod_cat
HAVING AVG(total_amt) > (SELECT AVG(total_amt) FROM Transactions)

--14. End

 
--Q15: Find the average and total revenue by each sub category for the categories which are among top 5 in terms of quantity sold.

SELECT prod_cat, prod_subcat, AVG(total_amt) AS AVG_AMT , SUM(total_amt) AS TOTAL_AMT
FROM Transactions AS T 
INNER JOIN prod_cat_info AS P 
ON T.prod_cat_code = P.prod_cat_code
		AND 
	T.prod_subcat_code = P.prod_sub_cat_code 
WHERE prod_cat IN 
	(SELECT TOP 5 prod_cat FROM Transactions AS T
	INNER JOIN prod_cat_info AS P
	ON T.prod_cat_code = P.prod_cat_code 
			AND
		T.prod_subcat_code = P.prod_sub_cat_code
	GROUP BY prod_cat
	ORDER BY SUM(Qty) DESC)
GROUP BY prod_cat,  prod_subcat
ORDER BY prod_cat

SELECT TOP 1 Store_type,COUNT(Store_type)  AS Trans_Count FROM Transactions
Group by Store_type
ORDER BY Trans_Count DESC

--15.End

 